sudo: required

language: cpp

services:
  - docker

before_install:
- docker pull sroycode/zapdos_build

script:
- docker run sroycode/zapdos /bin/sh -c "cd /app/zapdos_temp/zapdos-latest && git pull && mkdir -p build && cd build && cmake .. && make"
