sudo: required

language: cpp

services:
  - docker

before_install:
- docker pull --cache-from sroycode/zapdos_build:latest sroycode/zapdos_build:latest
- docker copy sroycode/zapdos sroycode/zapdos_build:/app/zapdos

script:
- docker run sroycode/zapdos_build /bin/bash -c "cd /app/zapdos && mkdir -p build && cd build && source /opt/rh/devtoolset-7/enable && cmake3 -DBOOST_ROOT=/opt/local/boost .. && make"
