sudo: required

language: cpp

services:
  - docker

branches:
  only:
  - master

before_install:
- docker pull sroycode/zapdos_build

script:
- docker run -v /home/travis/build/sroycode/zapdos:/app/zapdos sroycode/zapdos_build /bin/bash -c "cd /app/zapdos && ln -s /opt/local/zapdos/thirdparty . && mkdir -p build && cd build && source /opt/rh/devtoolset-7/enable && cmake3 -DBOOST_ROOT=/opt/local/boost .. && make"
