dist: bionic

addons:
  apt:
    sources:
      - ppa:exonum/rocksdb 
      - ppa:maarten-fonville/protobuf 
      - ppa:xapian-backports/ppa 
    packages:
      - ccache
      - cmake
      - make
      - libtool
      - pkg-config
      - g++
      - gcc
      - lcov
      - protobuf-compiler
      - libboost-all-dev
      - libcurl4-openssl-dev
      - zlib1g-dev
      - liblz4-dev
      - libprotobuf-dev
      - libgoogle-glog-dev
      - libgflags-dev
      - libgoogle-perftools-dev
      - libsnappy-dev
      - libbz2-dev
      - libz-dev
      - libctemplate-dev
      - libtbb-dev
      - libzstd-dev
      - libxapian-dev
      - libsodium-dev
      - libosmium-dev
      - librocksdb-dev
      - libpqxx-dev

language: cpp

branches:
  only:
  - master

before_install:
- locale-gen en_US.UTF-8 
- update-locale LANG=en_US.UTF-8 

script:
- mkdir -p build
- cd build
- cmake ..
- make
