# Docker File for Centos based zapdos

FROM centos:centos7
MAINTAINER S Roychowdhury <sroycode@gmail.com>

ENV LANG C

# Docker File for Centos based zapdos
RUN yum install -y deltarpm wget yum-utils centos-release-scl \
	https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm \
	&& yum -y update && yum clean all \
	&& yum -y install devtoolset-7-gcc devtoolset-7-gcc-c++ devtoolset-7-binutils \
	cmake3 glog-devel libunwind-devel libicu-devel libcurl-devel \
	wget curl python2-httpie autoconf automake libtool ccache \
	bzip2 zlib bzip2-devel zlib-devel tbb-devel glog-devel gflags-devel which \
	file make git libpqxx-devel nginx

# Build environment
ENV BOOST_ROOT /opt/local/boost
ENV ZAPDOS_SOURCE /app/zapdos
ENV ZAPDOS_TEMP /app/zapdos_temp
ENV ZAPDOS_DEPS /opt/local/zapdos
ENV ZAPDOS_TPSRC /opt/backup

ENV PATH ${PATH}:${ZAPDOS_DEPS}/thirdparty/bin
ENV CPPFLAGS -I/opt/local/include -I/usr/local/include -I${ZAPDOS_DEPS}/thirdparty/include
ENV CXXFLAGS -I/opt/local/include -I/usr/local/include -I${ZAPDOS_DEPS}/thirdparty/include
ENV LDFLAGS -L/opt/local/lib -L/usr/local/lib -L${ZAPDOS_DEPS}/thirdparty/lib
ENV LD_LIBRARY_PATH ${LD_LIBRARY_PATH}:${ZAPDOS_DEPS}/thirdparty/lib:${ZAPDOS_DEPS}/thirdparty/lib64
ENV PKG_CONFIG_PATH ${PKG_CONFIG_PATH}:${ZAPDOS_DEPS}/thirdparty/lib/pkgconfig:/usr/local/lib/pkgconfig
ENV CXXFLAGS -std=c++11

# Dependencies

WORKDIR ${ZAPDOS_TEMP}
RUN mkdir -p ${ZAPDOS_SOURCE} ${ZAPDOS_TEMP} ${ZAPDOS_DEPS} ${ZAPDOS_TPSRC}
COPY build_env.sh ${ZAPDOS_SOURCE}/build_env.sh
RUN bash ${ZAPDOS_SOURCE}/build_env.sh

### MAIN 

